# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ task-ci ]
  pull_request:
    branches: [ task-ci ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: update submodules and build
      shell: bash
      run: |
        git submodule update --init --recursive
        cd task-ci
        cmake -B_build
        cd _build
        make
        pwd

    - name: UploadArtifacts
      uses: actions/upload-artifact@v1
      with: 
        name: Distributive
        path: /home/runner/work/test/test/task-ci/bin

    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with:
        exec-path: "task-ci/bin/CTestExe"
        report-path: "report.xml"
        # working-directory: "./../"